name: Build libaapt2.so (ARM64, 16KB page)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build protobuf-compiler cmake p7zip-full

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          add-to-path: true
          
      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-29 \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja

      - name: Build libaapt2
        run: cmake --build build --config Release -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libaapt2
          path: build/libaapt2_bin.so
